export const INITIAL_SCHEMA_TABLES = [
  'analytics_events',
  'app_settings',
  'audit_events',
  'consent_records',
  'dependency_edges',
  'episode_version_shots',
  'episode_versions',
  'episodes',
  'evaluation_annotations',
  'evaluation_samples',
  'export_records',
  'finding_overrides',
  'format_profiles',
  'import_records',
  'lock_records',
  'model_invocations',
  'model_price_snapshots',
  'producibility_findings',
  'producibility_reports',
  'projects',
  'prompt_templates',
  'provider_capability_snapshots',
  'provider_profiles',
  'reference_price_snapshots',
  'schema_migrations',
  'schema_registry_manifest',
  'script_stage_jobs',
  'script_versions',
  'shot_contract_versions',
  'shot_derivations',
  'shots',
  'source_inputs',
  'stage_heads',
  'story_bible_versions',
] as const;

export const INITIAL_SCHEMA_INDEXES = [
  'ix_audit_project_time',
  'ix_dependency_downstream',
  'ix_dependency_upstream',
  'ix_evaluation_sample_type',
  'ix_export_episode_time',
  'ix_job_status_created',
  'ix_script_project_stage',
  'ix_shot_episode_lifecycle',
  'ix_shot_version_sequence',
  'ix_story_bible_project_version',
  'ux_episode_version_sequence',
  'ux_episode_version_shot_version',
  'ux_format_profile_current',
  'ux_import_success_idempotency',
  'ux_lock_active_pointer',
  'ux_one_active_episode_per_project',
  'ux_stage_heads_episode_level',
  'ux_stage_heads_project_level',
] as const;

export const INITIAL_SCHEMA_TRIGGERS = [
  'trg_episode_versions_immutable',
  'trg_script_versions_immutable',
  'trg_shot_contract_versions_immutable',
  'trg_story_bible_versions_immutable',
] as const;
