packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true

blockExoticSubdeps: true
engineStrict: true
nodeLinker: hoisted
packageManagerStrict: true
saveExact: true
strictDepBuilds: true

supportedArchitectures:
  os:
    - win32
  cpu:
    - x64
